alias hcurl='curl -H "user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0"'
alias l='ls -lh'
alias la='ls -a'
alias ll='ls -alh'
alias please='sudo'
alias poke='touch'
